/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BButton: typeof import('bootstrap-vue-next')['BButton']
    BCard: typeof import('bootstrap-vue-next')['BCard']
    BDropdownItem: typeof import('bootstrap-vue-next')['BDropdownItem']
    BForm: typeof import('bootstrap-vue-next')['BForm']
    BFormCheckbox: typeof import('bootstrap-vue-next')['BFormCheckbox']
    BFormCheckboxGroup: typeof import('bootstrap-vue-next')['BFormCheckboxGroup']
    BFormGroup: typeof import('bootstrap-vue-next')['BFormGroup']
    BFormInput: typeof import('bootstrap-vue-next')['BFormInput']
    BFormSelect: typeof import('bootstrap-vue-next')['BFormSelect']
    BIconArrowLeftSquareFill: typeof import('bootstrap-vue-next')['BIconArrowLeftSquareFill']
    BIconArrowRightSquareFill: typeof import('bootstrap-vue-next')['BIconArrowRightSquareFill']
    BNav: typeof import('bootstrap-vue-next')['BNav']
    BNavItem: typeof import('bootstrap-vue-next')['BNavItem']
    BNavItemDropdown: typeof import('bootstrap-vue-next')['BNavItemDropdown']
    GnbMenu: typeof import('./src/components/GnbMenu.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
